/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "ISR_UART_RX.h"
#include "UART_LOG.h"
#include "TFT_SDA_aliases.h"
#include "TFT_SDA.h"
#include "TFT_SCL_aliases.h"
#include "TFT_SCL.h"
#include "TFT_LED_aliases.h"
#include "TFT_LED.h"
#include "TFT_SPI.h"
#include "TFT_SPI_PVT.h"
#include "TFT_DC_aliases.h"
#include "TFT_DC.h"
#include "TFT_RES_aliases.h"
#include "TFT_RES.h"
#include "TFT_CS_aliases.h"
#include "TFT_CS.h"
#include "TFT_BackLight.h"
#include "PWM_Clock_TFT.h"
#include "UART_LOG_IntClock.h"
#include "TFT_SPI_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

